version: "0.1"

services:
  bankroller_core:
    container_name: bankroller_core
    labels:
      - "Bankroller instance"
    image: altvnv/bankroller-core:development-latest
    environment:
      - ACCOUNT_PRIVATE_KEY=${ACCOUNT_PRIVATE_KEY}
  dc_protocol:
    container_name: dc_protocol
    labels:
      - "testrpc with dao casino protocol contracts"
    image: altvnv/dc-protocol:development-latest
    environment:
      - hostname=0.0.0.0
      - port=8546
      # - defaultBalanceEther=100000
      # - blockTime=2
      # - gasPrice=1
      # - gasLimit=7992181
      # - mnemonic='candy, maple cake sugar pudding cream honey rich smooth crumble sweet treat'
    ports:
      - 8545:8546
    volumes:
      - ./src/build:/protocol
